<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="svenkat" name="Food-&gt;Create-&gt;Approve-&gt;Edittwo" tests="4" failures="1" timestamp="17 Nov 2012 21:27:31 GMT" time="33.563" errors="0">
  <testcase name="testCreateFood" time="18.057" classname="FoodScripts.TestFoodCreate"/>
  <testcase name="testDeducedMeasurementOfPrimaryMeasurementUnitInApprovalScreen" time="8.265" classname="FoodScripts.TestFoodSuperAdmin"/>
  <testcase name="testDeducedMeasureUnitsOfMl" time="0.093" classname="FoodScripts.TestDeducedMeasureUnits">
    <failure type="java.lang.AssertionError" message="The deduced measurement units of ML are not equal to 9 expected [9[ but found ]2]">
      <![CDATA[java.lang.AssertionError: The deduced measurement units of ML are not equal to 9 expected [9[ but found ]2]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:370)
	at FoodScripts.TestDeducedMeasureUnits.testDeducedMeasureUnitsOfMl(TestDeducedMeasureUnits.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1197)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1122)
	at org.testng.TestNG.run(TestNG.java:1030)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- testDeducedMeasureUnitsOfMl -->
  <testcase name="testEditFoodScreen" time="6.969" classname="FoodScripts.TestFoodEdit"/>
</testsuite> <!-- Food->Create->Approve->Edittwo -->
